// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE
'use strict';

var OtherModule = require("./OtherModule.bs.js");

console.log(OtherModule.a + OtherModule.b | 0);

/*  Not a pure module */
